title: Sujal Bhavsar, Ph.D.
description: >-
  Principal Machine Learning & Optimization Engineer | AI in Energy Systems | Electricity Markets | Forecasting | Optimization
theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/149137449?v=4   # optional: upload your profile photo to /assets/
show_downloads: false
google_analytics: ""        # Add your GA ID if you want tracking
